// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1229438603;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'helpmemove_bridge',
        ioDirectory: '../../crates/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  double crateApiBridgeAcceptConfidence({required double value});

  String crateApiBridgeAcceptEquipment({required String raw});

  String crateApiBridgeAcceptGoal({required String raw});

  String crateApiBridgeAcceptLaterality({required String raw});

  String crateApiBridgeAcceptRegion({required String raw});

  String crateApiBridgeAcceptSubject({required String raw});

  String crateApiBridgeBridgeVersion();

  SafetyView crateApiBridgeClassifyCommittedRule({
    required List<SafetyAnswer> answers,
    required PlatformInt64 nowUnixMillis,
    required List<String> triggers,
    required String emergencyRegion,
  });

  int crateApiBridgeConvertLengthMmToInchThousandths({
    required int millimeters,
  });

  PlatformInt64 crateApiBridgeElapsedMillis({
    required PlatformInt64 earlier,
    required PlatformInt64 later,
  });

  IntakeVocabulary crateApiBridgeIntakeVocabulary();

  void crateApiBridgeObserveCancel({required bool cancelled});

  String crateApiBridgeProbeContainedPanic();

  void crateApiBridgeRequireVersion({required String caller});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  double crateApiBridgeAcceptConfidence({required double value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptConfidenceConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptConfidenceConstMeta =>
      const TaskConstMeta(debugName: "accept_confidence", argNames: ["value"]);

  @override
  String crateApiBridgeAcceptEquipment({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptEquipmentConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptEquipmentConstMeta =>
      const TaskConstMeta(debugName: "accept_equipment", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptGoal({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptGoalConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptGoalConstMeta =>
      const TaskConstMeta(debugName: "accept_goal", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptLaterality({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptLateralityConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptLateralityConstMeta =>
      const TaskConstMeta(debugName: "accept_laterality", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptRegion({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptRegionConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptRegionConstMeta =>
      const TaskConstMeta(debugName: "accept_region", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptSubject({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptSubjectConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptSubjectConstMeta =>
      const TaskConstMeta(debugName: "accept_subject", argNames: ["raw"]);

  @override
  String crateApiBridgeBridgeVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeBridgeVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeBridgeVersionConstMeta =>
      const TaskConstMeta(debugName: "bridge_version", argNames: []);

  @override
  SafetyView crateApiBridgeClassifyCommittedRule({
    required List<SafetyAnswer> answers,
    required PlatformInt64 nowUnixMillis,
    required List<String> triggers,
    required String emergencyRegion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_safety_answer(answers, serializer);
          sse_encode_i_64(nowUnixMillis, serializer);
          sse_encode_list_String(triggers, serializer);
          sse_encode_String(emergencyRegion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_safety_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeClassifyCommittedRuleConstMeta,
        argValues: [answers, nowUnixMillis, triggers, emergencyRegion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeClassifyCommittedRuleConstMeta =>
      const TaskConstMeta(
        debugName: "classify_committed_rule",
        argNames: ["answers", "nowUnixMillis", "triggers", "emergencyRegion"],
      );

  @override
  int crateApiBridgeConvertLengthMmToInchThousandths({
    required int millimeters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(millimeters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeConvertLengthMmToInchThousandthsConstMeta,
        argValues: [millimeters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeConvertLengthMmToInchThousandthsConstMeta =>
      const TaskConstMeta(
        debugName: "convert_length_mm_to_inch_thousandths",
        argNames: ["millimeters"],
      );

  @override
  PlatformInt64 crateApiBridgeElapsedMillis({
    required PlatformInt64 earlier,
    required PlatformInt64 later,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(earlier, serializer);
          sse_encode_i_64(later, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeElapsedMillisConstMeta,
        argValues: [earlier, later],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeElapsedMillisConstMeta =>
      const TaskConstMeta(
        debugName: "elapsed_millis",
        argNames: ["earlier", "later"],
      );

  @override
  IntakeVocabulary crateApiBridgeIntakeVocabulary() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_intake_vocabulary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeIntakeVocabularyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeIntakeVocabularyConstMeta =>
      const TaskConstMeta(debugName: "intake_vocabulary", argNames: []);

  @override
  void crateApiBridgeObserveCancel({required bool cancelled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(cancelled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeObserveCancelConstMeta,
        argValues: [cancelled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeObserveCancelConstMeta =>
      const TaskConstMeta(debugName: "observe_cancel", argNames: ["cancelled"]);

  @override
  String crateApiBridgeProbeContainedPanic() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeProbeContainedPanicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeProbeContainedPanicConstMeta =>
      const TaskConstMeta(debugName: "probe_contained_panic", argNames: []);

  @override
  void crateApiBridgeRequireVersion({required String caller}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(caller, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeRequireVersionConstMeta,
        argValues: [caller],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeRequireVersionConstMeta =>
      const TaskConstMeta(debugName: "require_version", argNames: ["caller"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeError.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IntakeVocabulary dco_decode_intake_vocabulary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return IntakeVocabulary(
      regions: dco_decode_list_String(arr[0]),
      goals: dco_decode_list_String(arr[1]),
      equipment: dco_decode_list_String(arr[2]),
      lateralities: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SafetyAnswer> dco_decode_list_safety_answer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_safety_answer).toList();
  }

  @protected
  SafetyAnswer dco_decode_safety_answer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SafetyAnswer(
      token: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  SafetyView dco_decode_safety_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SafetyView(
      code: dco_decode_String(arr[0]),
      level: dco_decode_String(arr[1]),
      escalation: dco_decode_String(arr[2]),
      permitsOrdinaryGeneration: dco_decode_bool(arr[3]),
      emergencyDisplay: dco_decode_String(arr[4]),
      emergencyCode: dco_decode_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeError.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IntakeVocabulary sse_decode_intake_vocabulary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_regions = sse_decode_list_String(deserializer);
    var var_goals = sse_decode_list_String(deserializer);
    var var_equipment = sse_decode_list_String(deserializer);
    var var_lateralities = sse_decode_list_String(deserializer);
    return IntakeVocabulary(
      regions: var_regions,
      goals: var_goals,
      equipment: var_equipment,
      lateralities: var_lateralities,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SafetyAnswer> sse_decode_list_safety_answer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SafetyAnswer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_safety_answer(deserializer));
    }
    return ans_;
  }

  @protected
  SafetyAnswer sse_decode_safety_answer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return SafetyAnswer(token: var_token, value: var_value);
  }

  @protected
  SafetyView sse_decode_safety_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_level = sse_decode_String(deserializer);
    var var_escalation = sse_decode_String(deserializer);
    var var_permitsOrdinaryGeneration = sse_decode_bool(deserializer);
    var var_emergencyDisplay = sse_decode_String(deserializer);
    var var_emergencyCode = sse_decode_String(deserializer);
    return SafetyView(
      code: var_code,
      level: var_level,
      escalation: var_escalation,
      permitsOrdinaryGeneration: var_permitsOrdinaryGeneration,
      emergencyDisplay: var_emergencyDisplay,
      emergencyCode: var_emergencyCode,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_intake_vocabulary(
    IntakeVocabulary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.regions, serializer);
    sse_encode_list_String(self.goals, serializer);
    sse_encode_list_String(self.equipment, serializer);
    sse_encode_list_String(self.lateralities, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_safety_answer(
    List<SafetyAnswer> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_safety_answer(item, serializer);
    }
  }

  @protected
  void sse_encode_safety_answer(SafetyAnswer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_safety_view(SafetyView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.level, serializer);
    sse_encode_String(self.escalation, serializer);
    sse_encode_bool(self.permitsOrdinaryGeneration, serializer);
    sse_encode_String(self.emergencyDisplay, serializer);
    sse_encode_String(self.emergencyCode, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
