// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1333471971;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'helpmemove_bridge',
        ioDirectory: '../../crates/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  double crateApiBridgeAcceptConfidence({required double value});

  String crateApiBridgeAcceptEquipment({required String raw});

  String crateApiBridgeAcceptGoal({required String raw});

  String crateApiBridgeAcceptLaterality({required String raw});

  String crateApiBridgeAcceptRating({required String raw});

  String crateApiBridgeAcceptRegion({required String raw});

  String crateApiBridgeAcceptSubject({required String raw});

  WorkoutView crateApiBridgeApplyWorkoutEvent({
    required String documentJson,
    required String eventJson,
    required PlatformInt64 monotonicMillis,
  });

  AssessmentVocabulary crateApiBridgeAssessmentVocabulary();

  String crateApiBridgeBridgeVersion();

  SafetyView crateApiBridgeClassifyCommittedRule({
    required List<SafetyAnswer> answers,
    required PlatformInt64 nowUnixMillis,
    required List<String> triggers,
    required String emergencyRegion,
  });

  String crateApiBridgeCommittedDisableList();

  String crateApiBridgeCommittedDisableListSig();

  StartingPlan crateApiBridgeComposeStartingPlan({
    required String intakeDocument,
    required String assessmentDocument,
    required PlatformInt64 nowUnixMillis,
  });

  int crateApiBridgeConvertLengthMmToInchThousandths({
    required int millimeters,
  });

  PlatformInt64 crateApiBridgeElapsedMillis({
    required PlatformInt64 earlier,
    required PlatformInt64 later,
  });

  String crateApiBridgeEvaluateContentPack({
    required String manifestJson,
    required String signatureHex,
    required List<String> filePaths,
    required List<Uint8List> fileContents,
    required int floorVersion,
    required String disableListJson,
    required String disableListSigHex,
    required PlatformInt64 nowMs,
    required PlatformInt64 lastVerifiedAtMs,
    PlatformInt64? maxOfflineAgeMs,
  });

  ExerciseDisplay crateApiBridgeExerciseDisplay({required String exerciseId});

  IntakeVocabulary crateApiBridgeIntakeVocabulary();

  AssessmentInstrumentView crateApiBridgeLoadCommittedInstrument();

  ProgramRuleView crateApiBridgeLoadCommittedProgramRule();

  void crateApiBridgeObserveCancel({required bool cancelled});

  WorkoutView crateApiBridgeOpenWorkout({
    required String programJson,
    required PlatformInt64 monotonicMillis,
    required String sessionId,
  });

  AdaptationView crateApiBridgePrepareAdaptation({
    required String intakeJson,
    required String assessmentJson,
    required String programJson,
    required String workoutJson,
    required String readinessJson,
  });

  FlareView crateApiBridgePrepareFlareFollowup({
    required String intakeJson,
    required String assessmentJson,
    required String programJson,
    required String workoutJson,
    required String followupJson,
  });

  ProgressView crateApiBridgePrepareProgressSummary({
    required String entriesJson,
  });

  String crateApiBridgeProbeContainedPanic();

  List<String> crateApiBridgeRecalledSessions({
    required List<String> documents,
    required String disableListJson,
  });

  void crateApiBridgeRequireVersion({required String caller});

  String crateApiBridgeVerifyDisableList({
    required String json,
    required String signatureHex,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  double crateApiBridgeAcceptConfidence({required double value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptConfidenceConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptConfidenceConstMeta =>
      const TaskConstMeta(debugName: "accept_confidence", argNames: ["value"]);

  @override
  String crateApiBridgeAcceptEquipment({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptEquipmentConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptEquipmentConstMeta =>
      const TaskConstMeta(debugName: "accept_equipment", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptGoal({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptGoalConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptGoalConstMeta =>
      const TaskConstMeta(debugName: "accept_goal", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptLaterality({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptLateralityConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptLateralityConstMeta =>
      const TaskConstMeta(debugName: "accept_laterality", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptRating({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptRatingConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptRatingConstMeta =>
      const TaskConstMeta(debugName: "accept_rating", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptRegion({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptRegionConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptRegionConstMeta =>
      const TaskConstMeta(debugName: "accept_region", argNames: ["raw"]);

  @override
  String crateApiBridgeAcceptSubject({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeAcceptSubjectConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAcceptSubjectConstMeta =>
      const TaskConstMeta(debugName: "accept_subject", argNames: ["raw"]);

  @override
  WorkoutView crateApiBridgeApplyWorkoutEvent({
    required String documentJson,
    required String eventJson,
    required PlatformInt64 monotonicMillis,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentJson, serializer);
          sse_encode_String(eventJson, serializer);
          sse_encode_i_64(monotonicMillis, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workout_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeApplyWorkoutEventConstMeta,
        argValues: [documentJson, eventJson, monotonicMillis],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeApplyWorkoutEventConstMeta =>
      const TaskConstMeta(
        debugName: "apply_workout_event",
        argNames: ["documentJson", "eventJson", "monotonicMillis"],
      );

  @override
  AssessmentVocabulary crateApiBridgeAssessmentVocabulary() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_assessment_vocabulary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeAssessmentVocabularyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeAssessmentVocabularyConstMeta =>
      const TaskConstMeta(debugName: "assessment_vocabulary", argNames: []);

  @override
  String crateApiBridgeBridgeVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeBridgeVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeBridgeVersionConstMeta =>
      const TaskConstMeta(debugName: "bridge_version", argNames: []);

  @override
  SafetyView crateApiBridgeClassifyCommittedRule({
    required List<SafetyAnswer> answers,
    required PlatformInt64 nowUnixMillis,
    required List<String> triggers,
    required String emergencyRegion,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_safety_answer(answers, serializer);
          sse_encode_i_64(nowUnixMillis, serializer);
          sse_encode_list_String(triggers, serializer);
          sse_encode_String(emergencyRegion, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_safety_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeClassifyCommittedRuleConstMeta,
        argValues: [answers, nowUnixMillis, triggers, emergencyRegion],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeClassifyCommittedRuleConstMeta =>
      const TaskConstMeta(
        debugName: "classify_committed_rule",
        argNames: ["answers", "nowUnixMillis", "triggers", "emergencyRegion"],
      );

  @override
  String crateApiBridgeCommittedDisableList() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeCommittedDisableListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeCommittedDisableListConstMeta =>
      const TaskConstMeta(debugName: "committed_disable_list", argNames: []);

  @override
  String crateApiBridgeCommittedDisableListSig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeCommittedDisableListSigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeCommittedDisableListSigConstMeta =>
      const TaskConstMeta(
        debugName: "committed_disable_list_sig",
        argNames: [],
      );

  @override
  StartingPlan crateApiBridgeComposeStartingPlan({
    required String intakeDocument,
    required String assessmentDocument,
    required PlatformInt64 nowUnixMillis,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(intakeDocument, serializer);
          sse_encode_String(assessmentDocument, serializer);
          sse_encode_i_64(nowUnixMillis, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_starting_plan,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeComposeStartingPlanConstMeta,
        argValues: [intakeDocument, assessmentDocument, nowUnixMillis],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeComposeStartingPlanConstMeta =>
      const TaskConstMeta(
        debugName: "compose_starting_plan",
        argNames: ["intakeDocument", "assessmentDocument", "nowUnixMillis"],
      );

  @override
  int crateApiBridgeConvertLengthMmToInchThousandths({
    required int millimeters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(millimeters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeConvertLengthMmToInchThousandthsConstMeta,
        argValues: [millimeters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeConvertLengthMmToInchThousandthsConstMeta =>
      const TaskConstMeta(
        debugName: "convert_length_mm_to_inch_thousandths",
        argNames: ["millimeters"],
      );

  @override
  PlatformInt64 crateApiBridgeElapsedMillis({
    required PlatformInt64 earlier,
    required PlatformInt64 later,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(earlier, serializer);
          sse_encode_i_64(later, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeElapsedMillisConstMeta,
        argValues: [earlier, later],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeElapsedMillisConstMeta =>
      const TaskConstMeta(
        debugName: "elapsed_millis",
        argNames: ["earlier", "later"],
      );

  @override
  String crateApiBridgeEvaluateContentPack({
    required String manifestJson,
    required String signatureHex,
    required List<String> filePaths,
    required List<Uint8List> fileContents,
    required int floorVersion,
    required String disableListJson,
    required String disableListSigHex,
    required PlatformInt64 nowMs,
    required PlatformInt64 lastVerifiedAtMs,
    PlatformInt64? maxOfflineAgeMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(manifestJson, serializer);
          sse_encode_String(signatureHex, serializer);
          sse_encode_list_String(filePaths, serializer);
          sse_encode_list_list_prim_u_8_strict(fileContents, serializer);
          sse_encode_u_32(floorVersion, serializer);
          sse_encode_String(disableListJson, serializer);
          sse_encode_String(disableListSigHex, serializer);
          sse_encode_i_64(nowMs, serializer);
          sse_encode_i_64(lastVerifiedAtMs, serializer);
          sse_encode_opt_box_autoadd_i_64(maxOfflineAgeMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeEvaluateContentPackConstMeta,
        argValues: [
          manifestJson,
          signatureHex,
          filePaths,
          fileContents,
          floorVersion,
          disableListJson,
          disableListSigHex,
          nowMs,
          lastVerifiedAtMs,
          maxOfflineAgeMs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeEvaluateContentPackConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_content_pack",
        argNames: [
          "manifestJson",
          "signatureHex",
          "filePaths",
          "fileContents",
          "floorVersion",
          "disableListJson",
          "disableListSigHex",
          "nowMs",
          "lastVerifiedAtMs",
          "maxOfflineAgeMs",
        ],
      );

  @override
  ExerciseDisplay crateApiBridgeExerciseDisplay({required String exerciseId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(exerciseId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_exercise_display,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeExerciseDisplayConstMeta,
        argValues: [exerciseId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeExerciseDisplayConstMeta =>
      const TaskConstMeta(
        debugName: "exercise_display",
        argNames: ["exerciseId"],
      );

  @override
  IntakeVocabulary crateApiBridgeIntakeVocabulary() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_intake_vocabulary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeIntakeVocabularyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeIntakeVocabularyConstMeta =>
      const TaskConstMeta(debugName: "intake_vocabulary", argNames: []);

  @override
  AssessmentInstrumentView crateApiBridgeLoadCommittedInstrument() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_assessment_instrument_view,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeLoadCommittedInstrumentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeLoadCommittedInstrumentConstMeta =>
      const TaskConstMeta(debugName: "load_committed_instrument", argNames: []);

  @override
  ProgramRuleView crateApiBridgeLoadCommittedProgramRule() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_program_rule_view,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeLoadCommittedProgramRuleConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeLoadCommittedProgramRuleConstMeta =>
      const TaskConstMeta(
        debugName: "load_committed_program_rule",
        argNames: [],
      );

  @override
  void crateApiBridgeObserveCancel({required bool cancelled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(cancelled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeObserveCancelConstMeta,
        argValues: [cancelled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeObserveCancelConstMeta =>
      const TaskConstMeta(debugName: "observe_cancel", argNames: ["cancelled"]);

  @override
  WorkoutView crateApiBridgeOpenWorkout({
    required String programJson,
    required PlatformInt64 monotonicMillis,
    required String sessionId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(programJson, serializer);
          sse_encode_i_64(monotonicMillis, serializer);
          sse_encode_String(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workout_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeOpenWorkoutConstMeta,
        argValues: [programJson, monotonicMillis, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeOpenWorkoutConstMeta => const TaskConstMeta(
    debugName: "open_workout",
    argNames: ["programJson", "monotonicMillis", "sessionId"],
  );

  @override
  AdaptationView crateApiBridgePrepareAdaptation({
    required String intakeJson,
    required String assessmentJson,
    required String programJson,
    required String workoutJson,
    required String readinessJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(intakeJson, serializer);
          sse_encode_String(assessmentJson, serializer);
          sse_encode_String(programJson, serializer);
          sse_encode_String(workoutJson, serializer);
          sse_encode_String(readinessJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_adaptation_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgePrepareAdaptationConstMeta,
        argValues: [
          intakeJson,
          assessmentJson,
          programJson,
          workoutJson,
          readinessJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgePrepareAdaptationConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_adaptation",
        argNames: [
          "intakeJson",
          "assessmentJson",
          "programJson",
          "workoutJson",
          "readinessJson",
        ],
      );

  @override
  FlareView crateApiBridgePrepareFlareFollowup({
    required String intakeJson,
    required String assessmentJson,
    required String programJson,
    required String workoutJson,
    required String followupJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(intakeJson, serializer);
          sse_encode_String(assessmentJson, serializer);
          sse_encode_String(programJson, serializer);
          sse_encode_String(workoutJson, serializer);
          sse_encode_String(followupJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_flare_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgePrepareFlareFollowupConstMeta,
        argValues: [
          intakeJson,
          assessmentJson,
          programJson,
          workoutJson,
          followupJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgePrepareFlareFollowupConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_flare_followup",
        argNames: [
          "intakeJson",
          "assessmentJson",
          "programJson",
          "workoutJson",
          "followupJson",
        ],
      );

  @override
  ProgressView crateApiBridgePrepareProgressSummary({
    required String entriesJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entriesJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_view,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgePrepareProgressSummaryConstMeta,
        argValues: [entriesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgePrepareProgressSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_progress_summary",
        argNames: ["entriesJson"],
      );

  @override
  String crateApiBridgeProbeContainedPanic() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeProbeContainedPanicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeProbeContainedPanicConstMeta =>
      const TaskConstMeta(debugName: "probe_contained_panic", argNames: []);

  @override
  List<String> crateApiBridgeRecalledSessions({
    required List<String> documents,
    required String disableListJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(documents, serializer);
          sse_encode_String(disableListJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeRecalledSessionsConstMeta,
        argValues: [documents, disableListJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeRecalledSessionsConstMeta =>
      const TaskConstMeta(
        debugName: "recalled_sessions",
        argNames: ["documents", "disableListJson"],
      );

  @override
  void crateApiBridgeRequireVersion({required String caller}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(caller, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiBridgeRequireVersionConstMeta,
        argValues: [caller],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeRequireVersionConstMeta =>
      const TaskConstMeta(debugName: "require_version", argNames: ["caller"]);

  @override
  String crateApiBridgeVerifyDisableList({
    required String json,
    required String signatureHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          sse_encode_String(signatureHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeVerifyDisableListConstMeta,
        argValues: [json, signatureHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeVerifyDisableListConstMeta =>
      const TaskConstMeta(
        debugName: "verify_disable_list",
        argNames: ["json", "signatureHex"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AdaptationView dco_decode_adaptation_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AdaptationView(
      outcome: dco_decode_String(arr[0]),
      withholdCode: dco_decode_String(arr[1]),
      documentJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  AssessmentInstrumentView dco_decode_assessment_instrument_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AssessmentInstrumentView(
      instrumentId: dco_decode_String(arr[0]),
      instrumentVersion: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  AssessmentVocabulary dco_decode_assessment_vocabulary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AssessmentVocabulary(ratings: dco_decode_list_String(arr[0]));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeError.values[raw as int];
  }

  @protected
  ExerciseDisplay dco_decode_exercise_display(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExerciseDisplay(
      name: dco_decode_String(arr[0]),
      writtenInstructions: dco_decode_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FlareView dco_decode_flare_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FlareView(
      outcome: dco_decode_String(arr[0]),
      withholdCode: dco_decode_String(arr[1]),
      documentJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IntakeVocabulary dco_decode_intake_vocabulary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return IntakeVocabulary(
      regions: dco_decode_list_String(arr[0]),
      goals: dco_decode_list_String(arr[1]),
      equipment: dco_decode_list_String(arr[2]),
      lateralities: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SafetyAnswer> dco_decode_list_safety_answer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_safety_answer).toList();
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ProgramRuleView dco_decode_program_rule_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProgramRuleView(
      ruleId: dco_decode_String(arr[0]),
      ruleVersion: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  ProgressView dco_decode_progress_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProgressView(
      outcome: dco_decode_String(arr[0]),
      withholdCode: dco_decode_String(arr[1]),
      documentJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  SafetyAnswer dco_decode_safety_answer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SafetyAnswer(
      token: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  SafetyView dco_decode_safety_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SafetyView(
      code: dco_decode_String(arr[0]),
      level: dco_decode_String(arr[1]),
      escalation: dco_decode_String(arr[2]),
      permitsOrdinaryGeneration: dco_decode_bool(arr[3]),
      emergencyDisplay: dco_decode_String(arr[4]),
      emergencyCode: dco_decode_String(arr[5]),
    );
  }

  @protected
  StartingPlan dco_decode_starting_plan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StartingPlan(
      outcome: dco_decode_String(arr[0]),
      withholdCode: dco_decode_String(arr[1]),
      documentJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkoutView dco_decode_workout_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WorkoutView(
      outcome: dco_decode_String(arr[0]),
      errorCode: dco_decode_String(arr[1]),
      documentJson: dco_decode_String(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AdaptationView sse_decode_adaptation_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_String(deserializer);
    var var_withholdCode = sse_decode_String(deserializer);
    var var_documentJson = sse_decode_String(deserializer);
    return AdaptationView(
      outcome: var_outcome,
      withholdCode: var_withholdCode,
      documentJson: var_documentJson,
    );
  }

  @protected
  AssessmentInstrumentView sse_decode_assessment_instrument_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_instrumentId = sse_decode_String(deserializer);
    var var_instrumentVersion = sse_decode_i_64(deserializer);
    return AssessmentInstrumentView(
      instrumentId: var_instrumentId,
      instrumentVersion: var_instrumentVersion,
    );
  }

  @protected
  AssessmentVocabulary sse_decode_assessment_vocabulary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ratings = sse_decode_list_String(deserializer);
    return AssessmentVocabulary(ratings: var_ratings);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeError.values[inner];
  }

  @protected
  ExerciseDisplay sse_decode_exercise_display(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_writtenInstructions = sse_decode_String(deserializer);
    return ExerciseDisplay(
      name: var_name,
      writtenInstructions: var_writtenInstructions,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FlareView sse_decode_flare_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_String(deserializer);
    var var_withholdCode = sse_decode_String(deserializer);
    var var_documentJson = sse_decode_String(deserializer);
    return FlareView(
      outcome: var_outcome,
      withholdCode: var_withholdCode,
      documentJson: var_documentJson,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IntakeVocabulary sse_decode_intake_vocabulary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_regions = sse_decode_list_String(deserializer);
    var var_goals = sse_decode_list_String(deserializer);
    var var_equipment = sse_decode_list_String(deserializer);
    var var_lateralities = sse_decode_list_String(deserializer);
    return IntakeVocabulary(
      regions: var_regions,
      goals: var_goals,
      equipment: var_equipment,
      lateralities: var_lateralities,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SafetyAnswer> sse_decode_list_safety_answer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SafetyAnswer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_safety_answer(deserializer));
    }
    return ans_;
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgramRuleView sse_decode_program_rule_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ruleId = sse_decode_String(deserializer);
    var var_ruleVersion = sse_decode_i_64(deserializer);
    return ProgramRuleView(ruleId: var_ruleId, ruleVersion: var_ruleVersion);
  }

  @protected
  ProgressView sse_decode_progress_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_String(deserializer);
    var var_withholdCode = sse_decode_String(deserializer);
    var var_documentJson = sse_decode_String(deserializer);
    return ProgressView(
      outcome: var_outcome,
      withholdCode: var_withholdCode,
      documentJson: var_documentJson,
    );
  }

  @protected
  SafetyAnswer sse_decode_safety_answer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return SafetyAnswer(token: var_token, value: var_value);
  }

  @protected
  SafetyView sse_decode_safety_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_level = sse_decode_String(deserializer);
    var var_escalation = sse_decode_String(deserializer);
    var var_permitsOrdinaryGeneration = sse_decode_bool(deserializer);
    var var_emergencyDisplay = sse_decode_String(deserializer);
    var var_emergencyCode = sse_decode_String(deserializer);
    return SafetyView(
      code: var_code,
      level: var_level,
      escalation: var_escalation,
      permitsOrdinaryGeneration: var_permitsOrdinaryGeneration,
      emergencyDisplay: var_emergencyDisplay,
      emergencyCode: var_emergencyCode,
    );
  }

  @protected
  StartingPlan sse_decode_starting_plan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_String(deserializer);
    var var_withholdCode = sse_decode_String(deserializer);
    var var_documentJson = sse_decode_String(deserializer);
    return StartingPlan(
      outcome: var_outcome,
      withholdCode: var_withholdCode,
      documentJson: var_documentJson,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkoutView sse_decode_workout_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outcome = sse_decode_String(deserializer);
    var var_errorCode = sse_decode_String(deserializer);
    var var_documentJson = sse_decode_String(deserializer);
    return WorkoutView(
      outcome: var_outcome,
      errorCode: var_errorCode,
      documentJson: var_documentJson,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_adaptation_view(
    AdaptationView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outcome, serializer);
    sse_encode_String(self.withholdCode, serializer);
    sse_encode_String(self.documentJson, serializer);
  }

  @protected
  void sse_encode_assessment_instrument_view(
    AssessmentInstrumentView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.instrumentId, serializer);
    sse_encode_i_64(self.instrumentVersion, serializer);
  }

  @protected
  void sse_encode_assessment_vocabulary(
    AssessmentVocabulary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.ratings, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_exercise_display(
    ExerciseDisplay self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.writtenInstructions, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_flare_view(FlareView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outcome, serializer);
    sse_encode_String(self.withholdCode, serializer);
    sse_encode_String(self.documentJson, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_intake_vocabulary(
    IntakeVocabulary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.regions, serializer);
    sse_encode_list_String(self.goals, serializer);
    sse_encode_list_String(self.equipment, serializer);
    sse_encode_list_String(self.lateralities, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_safety_answer(
    List<SafetyAnswer> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_safety_answer(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_program_rule_view(
    ProgramRuleView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ruleId, serializer);
    sse_encode_i_64(self.ruleVersion, serializer);
  }

  @protected
  void sse_encode_progress_view(ProgressView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outcome, serializer);
    sse_encode_String(self.withholdCode, serializer);
    sse_encode_String(self.documentJson, serializer);
  }

  @protected
  void sse_encode_safety_answer(SafetyAnswer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_safety_view(SafetyView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.level, serializer);
    sse_encode_String(self.escalation, serializer);
    sse_encode_bool(self.permitsOrdinaryGeneration, serializer);
    sse_encode_String(self.emergencyDisplay, serializer);
    sse_encode_String(self.emergencyCode, serializer);
  }

  @protected
  void sse_encode_starting_plan(StartingPlan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outcome, serializer);
    sse_encode_String(self.withholdCode, serializer);
    sse_encode_String(self.documentJson, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workout_view(WorkoutView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outcome, serializer);
    sse_encode_String(self.errorCode, serializer);
    sse_encode_String(self.documentJson, serializer);
  }
}
