// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bridge.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdaptationView dco_decode_adaptation_view(dynamic raw);

  @protected
  AssessmentInstrumentView dco_decode_assessment_instrument_view(dynamic raw);

  @protected
  AssessmentVocabulary dco_decode_assessment_vocabulary(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  ExerciseDisplay dco_decode_exercise_display(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IntakeVocabulary dco_decode_intake_vocabulary(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SafetyAnswer> dco_decode_list_safety_answer(dynamic raw);

  @protected
  ProgramRuleView dco_decode_program_rule_view(dynamic raw);

  @protected
  SafetyAnswer dco_decode_safety_answer(dynamic raw);

  @protected
  SafetyView dco_decode_safety_view(dynamic raw);

  @protected
  StartingPlan dco_decode_starting_plan(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkoutView dco_decode_workout_view(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdaptationView sse_decode_adaptation_view(SseDeserializer deserializer);

  @protected
  AssessmentInstrumentView sse_decode_assessment_instrument_view(
    SseDeserializer deserializer,
  );

  @protected
  AssessmentVocabulary sse_decode_assessment_vocabulary(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  ExerciseDisplay sse_decode_exercise_display(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IntakeVocabulary sse_decode_intake_vocabulary(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SafetyAnswer> sse_decode_list_safety_answer(
    SseDeserializer deserializer,
  );

  @protected
  ProgramRuleView sse_decode_program_rule_view(SseDeserializer deserializer);

  @protected
  SafetyAnswer sse_decode_safety_answer(SseDeserializer deserializer);

  @protected
  SafetyView sse_decode_safety_view(SseDeserializer deserializer);

  @protected
  StartingPlan sse_decode_starting_plan(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkoutView sse_decode_workout_view(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adaptation_view(
    AdaptationView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_assessment_instrument_view(
    AssessmentInstrumentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_assessment_vocabulary(
    AssessmentVocabulary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_exercise_display(
    ExerciseDisplay self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_intake_vocabulary(
    IntakeVocabulary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_safety_answer(
    List<SafetyAnswer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_program_rule_view(
    ProgramRuleView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_safety_answer(SafetyAnswer self, SseSerializer serializer);

  @protected
  void sse_encode_safety_view(SafetyView self, SseSerializer serializer);

  @protected
  void sse_encode_starting_plan(StartingPlan self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workout_view(WorkoutView self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
