// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1948813267;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__bridge__accept_confidence_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_confidence",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_value = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_confidence(api_value)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__accept_equipment_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_equipment",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_equipment(api_raw)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__accept_goal_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_goal",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_goal(api_raw)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__accept_laterality_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_laterality",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_laterality(api_raw)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__accept_rating_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_rating",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_rating(api_raw)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__accept_region_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_region",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_region(api_raw)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__accept_subject_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "accept_subject",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_raw = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::accept_subject(api_raw)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__apply_workout_event_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "apply_workout_event",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_document_json = <String>::sse_decode(&mut deserializer);
            let api_event_json = <String>::sse_decode(&mut deserializer);
            let api_monotonic_millis = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::apply_workout_event(
                    api_document_json,
                    api_event_json,
                    api_monotonic_millis,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__assessment_vocabulary_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "assessment_vocabulary",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::assessment_vocabulary())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__bridge_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bridge_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::bridge_version())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__classify_committed_rule_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classify_committed_rule",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_answers =
                <Vec<crate::api::bridge::SafetyAnswer>>::sse_decode(&mut deserializer);
            let api_now_unix_millis = <i64>::sse_decode(&mut deserializer);
            let api_triggers = <Vec<String>>::sse_decode(&mut deserializer);
            let api_emergency_region = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::classify_committed_rule(
                    api_answers,
                    api_now_unix_millis,
                    api_triggers,
                    api_emergency_region,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__compose_starting_plan_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compose_starting_plan",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_intake_document = <String>::sse_decode(&mut deserializer);
            let api_assessment_document = <String>::sse_decode(&mut deserializer);
            let api_now_unix_millis = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::compose_starting_plan(
                    api_intake_document,
                    api_assessment_document,
                    api_now_unix_millis,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__convert_length_mm_to_inch_thousandths_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "convert_length_mm_to_inch_thousandths",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_millimeters = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok =
                    crate::api::bridge::convert_length_mm_to_inch_thousandths(api_millimeters)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__elapsed_millis_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "elapsed_millis",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_earlier = <i64>::sse_decode(&mut deserializer);
            let api_later = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::elapsed_millis(api_earlier, api_later)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__exercise_display_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "exercise_display",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_exercise_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::exercise_display(api_exercise_id)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__intake_vocabulary_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "intake_vocabulary",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::intake_vocabulary())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__load_committed_instrument_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_committed_instrument",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::load_committed_instrument()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__load_committed_program_rule_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_committed_program_rule",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::load_committed_program_rule()?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__observe_cancel_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "observe_cancel",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cancelled = <bool>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::observe_cancel(api_cancelled)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__open_workout_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_workout",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_program_json = <String>::sse_decode(&mut deserializer);
            let api_monotonic_millis = <i64>::sse_decode(&mut deserializer);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::open_workout(
                    api_program_json,
                    api_monotonic_millis,
                    api_session_id,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__prepare_adaptation_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prepare_adaptation",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_intake_json = <String>::sse_decode(&mut deserializer);
            let api_assessment_json = <String>::sse_decode(&mut deserializer);
            let api_program_json = <String>::sse_decode(&mut deserializer);
            let api_workout_json = <String>::sse_decode(&mut deserializer);
            let api_readiness_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::prepare_adaptation(
                    api_intake_json,
                    api_assessment_json,
                    api_program_json,
                    api_workout_json,
                    api_readiness_json,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__prepare_flare_followup_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prepare_flare_followup",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_intake_json = <String>::sse_decode(&mut deserializer);
            let api_assessment_json = <String>::sse_decode(&mut deserializer);
            let api_program_json = <String>::sse_decode(&mut deserializer);
            let api_workout_json = <String>::sse_decode(&mut deserializer);
            let api_followup_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::prepare_flare_followup(
                    api_intake_json,
                    api_assessment_json,
                    api_program_json,
                    api_workout_json,
                    api_followup_json,
                ))?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__probe_contained_panic_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "probe_contained_panic",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::bridge::probe_contained_panic())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bridge__require_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "require_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_caller = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, crate::api::bridge::BridgeError>((move || {
                let output_ok = crate::api::bridge::require_version(api_caller)?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::bridge::AdaptationView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <String>::sse_decode(deserializer);
        let mut var_withholdCode = <String>::sse_decode(deserializer);
        let mut var_documentJson = <String>::sse_decode(deserializer);
        return crate::api::bridge::AdaptationView {
            outcome: var_outcome,
            withhold_code: var_withholdCode,
            document_json: var_documentJson,
        };
    }
}

impl SseDecode for crate::api::bridge::AssessmentInstrumentView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_instrumentId = <String>::sse_decode(deserializer);
        let mut var_instrumentVersion = <i64>::sse_decode(deserializer);
        return crate::api::bridge::AssessmentInstrumentView {
            instrument_id: var_instrumentId,
            instrument_version: var_instrumentVersion,
        };
    }
}

impl SseDecode for crate::api::bridge::AssessmentVocabulary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ratings = <Vec<String>>::sse_decode(deserializer);
        return crate::api::bridge::AssessmentVocabulary {
            ratings: var_ratings,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::bridge::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::bridge::BridgeError::InvalidSubjectId,
            1 => crate::api::bridge::BridgeError::InvalidLaterality,
            2 => crate::api::bridge::BridgeError::InvalidConfidence,
            3 => crate::api::bridge::BridgeError::InvalidLength,
            4 => crate::api::bridge::BridgeError::ClockWentBackwards,
            5 => crate::api::bridge::BridgeError::VersionMismatch,
            6 => crate::api::bridge::BridgeError::Cancelled,
            7 => crate::api::bridge::BridgeError::InvalidRegion,
            8 => crate::api::bridge::BridgeError::InvalidGoal,
            9 => crate::api::bridge::BridgeError::InvalidEquipment,
            10 => crate::api::bridge::BridgeError::InvalidRating,
            11 => crate::api::bridge::BridgeError::InvalidInstrument,
            12 => crate::api::bridge::BridgeError::InvalidProgram,
            _ => unreachable!("Invalid variant for BridgeError: {}", inner),
        };
    }
}

impl SseDecode for crate::api::bridge::ExerciseDisplay {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_writtenInstructions = <String>::sse_decode(deserializer);
        return crate::api::bridge::ExerciseDisplay {
            name: var_name,
            written_instructions: var_writtenInstructions,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::bridge::FlareView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <String>::sse_decode(deserializer);
        let mut var_withholdCode = <String>::sse_decode(deserializer);
        let mut var_documentJson = <String>::sse_decode(deserializer);
        return crate::api::bridge::FlareView {
            outcome: var_outcome,
            withhold_code: var_withholdCode,
            document_json: var_documentJson,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::bridge::IntakeVocabulary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_regions = <Vec<String>>::sse_decode(deserializer);
        let mut var_goals = <Vec<String>>::sse_decode(deserializer);
        let mut var_equipment = <Vec<String>>::sse_decode(deserializer);
        let mut var_lateralities = <Vec<String>>::sse_decode(deserializer);
        return crate::api::bridge::IntakeVocabulary {
            regions: var_regions,
            goals: var_goals,
            equipment: var_equipment,
            lateralities: var_lateralities,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::bridge::SafetyAnswer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::bridge::SafetyAnswer>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::bridge::ProgramRuleView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ruleId = <String>::sse_decode(deserializer);
        let mut var_ruleVersion = <i64>::sse_decode(deserializer);
        return crate::api::bridge::ProgramRuleView {
            rule_id: var_ruleId,
            rule_version: var_ruleVersion,
        };
    }
}

impl SseDecode for crate::api::bridge::SafetyAnswer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_token = <String>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        return crate::api::bridge::SafetyAnswer {
            token: var_token,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::bridge::SafetyView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <String>::sse_decode(deserializer);
        let mut var_level = <String>::sse_decode(deserializer);
        let mut var_escalation = <String>::sse_decode(deserializer);
        let mut var_permitsOrdinaryGeneration = <bool>::sse_decode(deserializer);
        let mut var_emergencyDisplay = <String>::sse_decode(deserializer);
        let mut var_emergencyCode = <String>::sse_decode(deserializer);
        return crate::api::bridge::SafetyView {
            code: var_code,
            level: var_level,
            escalation: var_escalation,
            permits_ordinary_generation: var_permitsOrdinaryGeneration,
            emergency_display: var_emergencyDisplay,
            emergency_code: var_emergencyCode,
        };
    }
}

impl SseDecode for crate::api::bridge::StartingPlan {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <String>::sse_decode(deserializer);
        let mut var_withholdCode = <String>::sse_decode(deserializer);
        let mut var_documentJson = <String>::sse_decode(deserializer);
        return crate::api::bridge::StartingPlan {
            outcome: var_outcome,
            withhold_code: var_withholdCode,
            document_json: var_documentJson,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::bridge::WorkoutView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outcome = <String>::sse_decode(deserializer);
        let mut var_errorCode = <String>::sse_decode(deserializer);
        let mut var_documentJson = <String>::sse_decode(deserializer);
        return crate::api::bridge::WorkoutView {
            outcome: var_outcome,
            error_code: var_errorCode,
            document_json: var_documentJson,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__bridge__accept_confidence_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__bridge__accept_equipment_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__bridge__accept_goal_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__bridge__accept_laterality_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__bridge__accept_rating_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__bridge__accept_region_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__bridge__accept_subject_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__bridge__apply_workout_event_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__bridge__assessment_vocabulary_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__bridge__bridge_version_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api__bridge__classify_committed_rule_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__bridge__compose_starting_plan_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__bridge__convert_length_mm_to_inch_thousandths_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        14 => wire__crate__api__bridge__elapsed_millis_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__bridge__exercise_display_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__bridge__intake_vocabulary_impl(ptr, rust_vec_len, data_len),
        17 => wire__crate__api__bridge__load_committed_instrument_impl(ptr, rust_vec_len, data_len),
        18 => {
            wire__crate__api__bridge__load_committed_program_rule_impl(ptr, rust_vec_len, data_len)
        }
        19 => wire__crate__api__bridge__observe_cancel_impl(ptr, rust_vec_len, data_len),
        20 => wire__crate__api__bridge__open_workout_impl(ptr, rust_vec_len, data_len),
        21 => wire__crate__api__bridge__prepare_adaptation_impl(ptr, rust_vec_len, data_len),
        22 => wire__crate__api__bridge__prepare_flare_followup_impl(ptr, rust_vec_len, data_len),
        23 => wire__crate__api__bridge__probe_contained_panic_impl(ptr, rust_vec_len, data_len),
        24 => wire__crate__api__bridge__require_version_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::AdaptationView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.withhold_code.into_into_dart().into_dart(),
            self.document_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::AdaptationView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::AdaptationView>
    for crate::api::bridge::AdaptationView
{
    fn into_into_dart(self) -> crate::api::bridge::AdaptationView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::AssessmentInstrumentView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.instrument_id.into_into_dart().into_dart(),
            self.instrument_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::AssessmentInstrumentView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::AssessmentInstrumentView>
    for crate::api::bridge::AssessmentInstrumentView
{
    fn into_into_dart(self) -> crate::api::bridge::AssessmentInstrumentView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::AssessmentVocabulary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.ratings.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::AssessmentVocabulary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::AssessmentVocabulary>
    for crate::api::bridge::AssessmentVocabulary
{
    fn into_into_dart(self) -> crate::api::bridge::AssessmentVocabulary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::BridgeError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidSubjectId => 0.into_dart(),
            Self::InvalidLaterality => 1.into_dart(),
            Self::InvalidConfidence => 2.into_dart(),
            Self::InvalidLength => 3.into_dart(),
            Self::ClockWentBackwards => 4.into_dart(),
            Self::VersionMismatch => 5.into_dart(),
            Self::Cancelled => 6.into_dart(),
            Self::InvalidRegion => 7.into_dart(),
            Self::InvalidGoal => 8.into_dart(),
            Self::InvalidEquipment => 9.into_dart(),
            Self::InvalidRating => 10.into_dart(),
            Self::InvalidInstrument => 11.into_dart(),
            Self::InvalidProgram => 12.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::BridgeError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::BridgeError>
    for crate::api::bridge::BridgeError
{
    fn into_into_dart(self) -> crate::api::bridge::BridgeError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::ExerciseDisplay {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.written_instructions.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::ExerciseDisplay
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::ExerciseDisplay>
    for crate::api::bridge::ExerciseDisplay
{
    fn into_into_dart(self) -> crate::api::bridge::ExerciseDisplay {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::FlareView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.withhold_code.into_into_dart().into_dart(),
            self.document_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge::FlareView {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::FlareView>
    for crate::api::bridge::FlareView
{
    fn into_into_dart(self) -> crate::api::bridge::FlareView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::IntakeVocabulary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.regions.into_into_dart().into_dart(),
            self.goals.into_into_dart().into_dart(),
            self.equipment.into_into_dart().into_dart(),
            self.lateralities.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::IntakeVocabulary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::IntakeVocabulary>
    for crate::api::bridge::IntakeVocabulary
{
    fn into_into_dart(self) -> crate::api::bridge::IntakeVocabulary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::ProgramRuleView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.rule_id.into_into_dart().into_dart(),
            self.rule_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::ProgramRuleView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::ProgramRuleView>
    for crate::api::bridge::ProgramRuleView
{
    fn into_into_dart(self) -> crate::api::bridge::ProgramRuleView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::SafetyAnswer {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.token.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::SafetyAnswer
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::SafetyAnswer>
    for crate::api::bridge::SafetyAnswer
{
    fn into_into_dart(self) -> crate::api::bridge::SafetyAnswer {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::SafetyView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.level.into_into_dart().into_dart(),
            self.escalation.into_into_dart().into_dart(),
            self.permits_ordinary_generation
                .into_into_dart()
                .into_dart(),
            self.emergency_display.into_into_dart().into_dart(),
            self.emergency_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::SafetyView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::SafetyView>
    for crate::api::bridge::SafetyView
{
    fn into_into_dart(self) -> crate::api::bridge::SafetyView {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::StartingPlan {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.withhold_code.into_into_dart().into_dart(),
            self.document_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::StartingPlan
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::StartingPlan>
    for crate::api::bridge::StartingPlan
{
    fn into_into_dart(self) -> crate::api::bridge::StartingPlan {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::bridge::WorkoutView {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.outcome.into_into_dart().into_dart(),
            self.error_code.into_into_dart().into_dart(),
            self.document_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::bridge::WorkoutView
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge::WorkoutView>
    for crate::api::bridge::WorkoutView
{
    fn into_into_dart(self) -> crate::api::bridge::WorkoutView {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::bridge::AdaptationView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.outcome, serializer);
        <String>::sse_encode(self.withhold_code, serializer);
        <String>::sse_encode(self.document_json, serializer);
    }
}

impl SseEncode for crate::api::bridge::AssessmentInstrumentView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.instrument_id, serializer);
        <i64>::sse_encode(self.instrument_version, serializer);
    }
}

impl SseEncode for crate::api::bridge::AssessmentVocabulary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.ratings, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::bridge::BridgeError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::bridge::BridgeError::InvalidSubjectId => 0,
                crate::api::bridge::BridgeError::InvalidLaterality => 1,
                crate::api::bridge::BridgeError::InvalidConfidence => 2,
                crate::api::bridge::BridgeError::InvalidLength => 3,
                crate::api::bridge::BridgeError::ClockWentBackwards => 4,
                crate::api::bridge::BridgeError::VersionMismatch => 5,
                crate::api::bridge::BridgeError::Cancelled => 6,
                crate::api::bridge::BridgeError::InvalidRegion => 7,
                crate::api::bridge::BridgeError::InvalidGoal => 8,
                crate::api::bridge::BridgeError::InvalidEquipment => 9,
                crate::api::bridge::BridgeError::InvalidRating => 10,
                crate::api::bridge::BridgeError::InvalidInstrument => 11,
                crate::api::bridge::BridgeError::InvalidProgram => 12,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::bridge::ExerciseDisplay {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.written_instructions, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::bridge::FlareView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.outcome, serializer);
        <String>::sse_encode(self.withhold_code, serializer);
        <String>::sse_encode(self.document_json, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::bridge::IntakeVocabulary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.regions, serializer);
        <Vec<String>>::sse_encode(self.goals, serializer);
        <Vec<String>>::sse_encode(self.equipment, serializer);
        <Vec<String>>::sse_encode(self.lateralities, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::bridge::SafetyAnswer> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::bridge::SafetyAnswer>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::bridge::ProgramRuleView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.rule_id, serializer);
        <i64>::sse_encode(self.rule_version, serializer);
    }
}

impl SseEncode for crate::api::bridge::SafetyAnswer {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.token, serializer);
        <String>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::bridge::SafetyView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.level, serializer);
        <String>::sse_encode(self.escalation, serializer);
        <bool>::sse_encode(self.permits_ordinary_generation, serializer);
        <String>::sse_encode(self.emergency_display, serializer);
        <String>::sse_encode(self.emergency_code, serializer);
    }
}

impl SseEncode for crate::api::bridge::StartingPlan {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.outcome, serializer);
        <String>::sse_encode(self.withhold_code, serializer);
        <String>::sse_encode(self.document_json, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::bridge::WorkoutView {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.outcome, serializer);
        <String>::sse_encode(self.error_code, serializer);
        <String>::sse_encode(self.document_json, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
