// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `adaptation_withheld`, `decision_fields`, `eligible_substitutions`, `embedded_exercises`, `emergency_fields`, `escalation_name`, `flare_withheld`, `instrument_view`, `program_rule_view`, `progress_withheld`, `ready`, `sorted`, `triage_name`, `withheld_plan`, `withheld`, `workout_from_content`, `workout_ready`, `workout_unavailable`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProgramSelection`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `active_issues_for_areas`, `code`, `select_program`

String bridgeVersion() => RustLib.instance.api.crateApiBridgeBridgeVersion();

String acceptSubject({required String raw}) =>
    RustLib.instance.api.crateApiBridgeAcceptSubject(raw: raw);

String acceptLaterality({required String raw}) =>
    RustLib.instance.api.crateApiBridgeAcceptLaterality(raw: raw);

double acceptConfidence({required double value}) =>
    RustLib.instance.api.crateApiBridgeAcceptConfidence(value: value);

PoseFrame acceptPoseFrame({
  required List<double> x,
  required List<double> y,
  required List<double> z,
  required List<double> visibility,
  required List<double> presence,
  required PlatformInt64 timestampUnixMs,
  required int rotationDegrees,
  required bool mirrored,
}) => RustLib.instance.api.crateApiBridgeAcceptPoseFrame(
  x: x,
  y: y,
  z: z,
  visibility: visibility,
  presence: presence,
  timestampUnixMs: timestampUnixMs,
  rotationDegrees: rotationDegrees,
  mirrored: mirrored,
);

int convertLengthMmToInchThousandths({required int millimeters}) => RustLib
    .instance
    .api
    .crateApiBridgeConvertLengthMmToInchThousandths(millimeters: millimeters);

PlatformInt64 elapsedMillis({
  required PlatformInt64 earlier,
  required PlatformInt64 later,
}) => RustLib.instance.api.crateApiBridgeElapsedMillis(
  earlier: earlier,
  later: later,
);

void requireVersion({required String caller}) =>
    RustLib.instance.api.crateApiBridgeRequireVersion(caller: caller);

void observeCancel({required bool cancelled}) =>
    RustLib.instance.api.crateApiBridgeObserveCancel(cancelled: cancelled);

String probeContainedPanic() =>
    RustLib.instance.api.crateApiBridgeProbeContainedPanic();

IntakeVocabulary intakeVocabulary() =>
    RustLib.instance.api.crateApiBridgeIntakeVocabulary();

String acceptRegion({required String raw}) =>
    RustLib.instance.api.crateApiBridgeAcceptRegion(raw: raw);

String acceptGoal({required String raw}) =>
    RustLib.instance.api.crateApiBridgeAcceptGoal(raw: raw);

String acceptEquipment({required String raw}) =>
    RustLib.instance.api.crateApiBridgeAcceptEquipment(raw: raw);

/// Classify the committed synthetic rule. The note and severity are not parameters.
SafetyView classifyCommittedRule({
  required List<SafetyAnswer> answers,
  required PlatformInt64 nowUnixMillis,
  required List<String> triggers,
  required String emergencyRegion,
}) => RustLib.instance.api.crateApiBridgeClassifyCommittedRule(
  answers: answers,
  nowUnixMillis: nowUnixMillis,
  triggers: triggers,
  emergencyRegion: emergencyRegion,
);

/// Ratings in fixture order. This list is not sorted.
AssessmentVocabulary assessmentVocabulary() =>
    RustLib.instance.api.crateApiBridgeAssessmentVocabulary();

/// Accept a movement-rating token. Invalid input does not echo the raw value.
String acceptRating({required String raw}) =>
    RustLib.instance.api.crateApiBridgeAcceptRating(raw: raw);

/// Load the committed fixture id and version. A parse failure is `InvalidInstrument`.
AssessmentInstrumentView loadCommittedInstrument() =>
    RustLib.instance.api.crateApiBridgeLoadCommittedInstrument();

/// Load the committed program fixture id and version. A parse failure is `InvalidProgram`.
ProgramRuleView loadCommittedProgramRule() =>
    RustLib.instance.api.crateApiBridgeLoadCommittedProgramRule();

/// Name and written instructions for one embedded fixture. Unknown ids stay out of the error.
ExerciseDisplay exerciseDisplay({required String exerciseId}) =>
    RustLib.instance.api.crateApiBridgeExerciseDisplay(exerciseId: exerciseId);

/// Classify the committed rule with `schema_ack=yes` only, then select.
///
/// The production answer does not permit ordinary generation.
StartingPlan composeStartingPlan({
  required String intakeDocument,
  required String assessmentDocument,
  required PlatformInt64 nowUnixMillis,
}) => RustLib.instance.api.crateApiBridgeComposeStartingPlan(
  intakeDocument: intakeDocument,
  assessmentDocument: assessmentDocument,
  nowUnixMillis: nowUnixMillis,
);

/// Open a synthetic session from a stored program row.
///
/// Counts come from the embedded fixtures. This does not classify or screen.
WorkoutView openWorkout({
  required String programJson,
  required PlatformInt64 monotonicMillis,
  required String sessionId,
}) => RustLib.instance.api.crateApiBridgeOpenWorkout(
  programJson: programJson,
  monotonicMillis: monotonicMillis,
  sessionId: sessionId,
);

/// Apply one manual event. A substitute is screened here; content does not call safety.
///
/// The production classification is `schema_ack=yes` only, so the eligible list is empty.
WorkoutView applyWorkoutEvent({
  required String documentJson,
  required String eventJson,
  required PlatformInt64 monotonicMillis,
}) => RustLib.instance.api.crateApiBridgeApplyWorkoutEvent(
  documentJson: documentJson,
  eventJson: eventJson,
  monotonicMillis: monotonicMillis,
);

/// Decide the next session from stored documents. Flutter passes no eligible list.
AdaptationView prepareAdaptation({
  required String intakeJson,
  required String assessmentJson,
  required String programJson,
  required String workoutJson,
  required String readinessJson,
}) => RustLib.instance.api.crateApiBridgePrepareAdaptation(
  intakeJson: intakeJson,
  assessmentJson: assessmentJson,
  programJson: programJson,
  workoutJson: workoutJson,
  readinessJson: readinessJson,
);

/// Decide the follow-up from stored documents. Flutter passes no eligible list.
FlareView prepareFlareFollowup({
  required String intakeJson,
  required String assessmentJson,
  required String programJson,
  required String workoutJson,
  required String followupJson,
}) => RustLib.instance.api.crateApiBridgePrepareFlareFollowup(
  intakeJson: intakeJson,
  assessmentJson: assessmentJson,
  programJson: programJson,
  workoutJson: workoutJson,
  followupJson: followupJson,
);

/// Count stored session rows. Flutter passes the entry list and no library.
ProgressView prepareProgressSummary({required String entriesJson}) => RustLib
    .instance
    .api
    .crateApiBridgePrepareProgressSummary(entriesJson: entriesJson);

String committedDisableList() =>
    RustLib.instance.api.crateApiBridgeCommittedDisableList();

String committedDisableListSig() =>
    RustLib.instance.api.crateApiBridgeCommittedDisableListSig();

String verifyDisableList({
  required String json,
  required String signatureHex,
}) => RustLib.instance.api.crateApiBridgeVerifyDisableList(
  json: json,
  signatureHex: signatureHex,
);

List<String> recalledSessions({
  required List<String> documents,
  required String disableListJson,
}) => RustLib.instance.api.crateApiBridgeRecalledSessions(
  documents: documents,
  disableListJson: disableListJson,
);

String evaluateContentPack({
  required String manifestJson,
  required String signatureHex,
  required List<String> filePaths,
  required List<Uint8List> fileContents,
  required int floorVersion,
  required String disableListJson,
  required String disableListSigHex,
  required PlatformInt64 nowMs,
  required PlatformInt64 lastVerifiedAtMs,
  PlatformInt64? maxOfflineAgeMs,
}) => RustLib.instance.api.crateApiBridgeEvaluateContentPack(
  manifestJson: manifestJson,
  signatureHex: signatureHex,
  filePaths: filePaths,
  fileContents: fileContents,
  floorVersion: floorVersion,
  disableListJson: disableListJson,
  disableListSigHex: disableListSigHex,
  nowMs: nowMs,
  lastVerifiedAtMs: lastVerifiedAtMs,
  maxOfflineAgeMs: maxOfflineAgeMs,
);

class AdaptationView {
  final String outcome;
  final String withholdCode;
  final String documentJson;

  const AdaptationView({
    required this.outcome,
    required this.withholdCode,
    required this.documentJson,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^ withholdCode.hashCode ^ documentJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdaptationView &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          withholdCode == other.withholdCode &&
          documentJson == other.documentJson;
}

class AssessmentInstrumentView {
  final String instrumentId;
  final PlatformInt64 instrumentVersion;

  const AssessmentInstrumentView({
    required this.instrumentId,
    required this.instrumentVersion,
  });

  @override
  int get hashCode => instrumentId.hashCode ^ instrumentVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssessmentInstrumentView &&
          runtimeType == other.runtimeType &&
          instrumentId == other.instrumentId &&
          instrumentVersion == other.instrumentVersion;
}

class AssessmentVocabulary {
  final List<String> ratings;

  const AssessmentVocabulary({required this.ratings});

  @override
  int get hashCode => ratings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssessmentVocabulary &&
          runtimeType == other.runtimeType &&
          ratings == other.ratings;
}

enum BridgeError {
  invalidSubjectId,
  invalidLaterality,
  invalidConfidence,
  invalidLength,
  clockWentBackwards,
  versionMismatch,
  cancelled,
  invalidRegion,
  invalidGoal,
  invalidEquipment,
  invalidRating,
  invalidInstrument,
  invalidProgram,
  invalidPoseFrame,
}

class ExerciseDisplay {
  final String name;
  final String writtenInstructions;

  const ExerciseDisplay({
    required this.name,
    required this.writtenInstructions,
  });

  @override
  int get hashCode => name.hashCode ^ writtenInstructions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExerciseDisplay &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          writtenInstructions == other.writtenInstructions;
}

class FlareView {
  final String outcome;
  final String withholdCode;
  final String documentJson;

  const FlareView({
    required this.outcome,
    required this.withholdCode,
    required this.documentJson,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^ withholdCode.hashCode ^ documentJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlareView &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          withholdCode == other.withholdCode &&
          documentJson == other.documentJson;
}

class IntakeVocabulary {
  final List<String> regions;
  final List<String> goals;
  final List<String> equipment;
  final List<String> lateralities;

  const IntakeVocabulary({
    required this.regions,
    required this.goals,
    required this.equipment,
    required this.lateralities,
  });

  @override
  int get hashCode =>
      regions.hashCode ^
      goals.hashCode ^
      equipment.hashCode ^
      lateralities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntakeVocabulary &&
          runtimeType == other.runtimeType &&
          regions == other.regions &&
          goals == other.goals &&
          equipment == other.equipment &&
          lateralities == other.lateralities;
}

/// Thirty-three landmarks and the caller timestamp. No image bytes.
class PoseFrame {
  final PlatformInt64 timestampUnixMs;
  final List<PosePoint> points;

  const PoseFrame({required this.timestampUnixMs, required this.points});

  @override
  int get hashCode => timestampUnixMs.hashCode ^ points.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PoseFrame &&
          runtimeType == other.runtimeType &&
          timestampUnixMs == other.timestampUnixMs &&
          points == other.points;
}

/// One landmark. `z` has no angle meaning.
class PosePoint {
  final double x;
  final double y;
  final double z;
  final double visibility;
  final double presence;

  const PosePoint({
    required this.x,
    required this.y,
    required this.z,
    required this.visibility,
    required this.presence,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      z.hashCode ^
      visibility.hashCode ^
      presence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PosePoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          z == other.z &&
          visibility == other.visibility &&
          presence == other.presence;
}

class ProgramRuleView {
  final String ruleId;
  final PlatformInt64 ruleVersion;

  const ProgramRuleView({required this.ruleId, required this.ruleVersion});

  @override
  int get hashCode => ruleId.hashCode ^ ruleVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgramRuleView &&
          runtimeType == other.runtimeType &&
          ruleId == other.ruleId &&
          ruleVersion == other.ruleVersion;
}

class ProgressView {
  final String outcome;
  final String withholdCode;
  final String documentJson;

  const ProgressView({
    required this.outcome,
    required this.withholdCode,
    required this.documentJson,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^ withholdCode.hashCode ^ documentJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressView &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          withholdCode == other.withholdCode &&
          documentJson == other.documentJson;
}

class SafetyAnswer {
  final String token;
  final String value;

  const SafetyAnswer({required this.token, required this.value});

  @override
  int get hashCode => token.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyAnswer &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          value == other.value;
}

class SafetyView {
  final String code;
  final String level;
  final String escalation;
  final bool permitsOrdinaryGeneration;
  final String emergencyDisplay;
  final String emergencyCode;

  const SafetyView({
    required this.code,
    required this.level,
    required this.escalation,
    required this.permitsOrdinaryGeneration,
    required this.emergencyDisplay,
    required this.emergencyCode,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      level.hashCode ^
      escalation.hashCode ^
      permitsOrdinaryGeneration.hashCode ^
      emergencyDisplay.hashCode ^
      emergencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SafetyView &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          level == other.level &&
          escalation == other.escalation &&
          permitsOrdinaryGeneration == other.permitsOrdinaryGeneration &&
          emergencyDisplay == other.emergencyDisplay &&
          emergencyCode == other.emergencyCode;
}

class StartingPlan {
  final String outcome;
  final String withholdCode;
  final String documentJson;

  const StartingPlan({
    required this.outcome,
    required this.withholdCode,
    required this.documentJson,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^ withholdCode.hashCode ^ documentJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartingPlan &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          withholdCode == other.withholdCode &&
          documentJson == other.documentJson;
}

class WorkoutView {
  final String outcome;
  final String errorCode;
  final String documentJson;

  const WorkoutView({
    required this.outcome,
    required this.errorCode,
    required this.documentJson,
  });

  @override
  int get hashCode =>
      outcome.hashCode ^ errorCode.hashCode ^ documentJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkoutView &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          errorCode == other.errorCode &&
          documentJson == other.documentJson;
}
